version: '3.6'

name: wiremock
services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./data:/home/wiremock
    command:
      - --verbose
      - --global-response-templating
